backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections: # A list of collections the CMS should be able to edit
  - name: "teas" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tea" # Used in the UI, ie.: "New Post"
    folder: "content/teas"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string", tagname: "h2"}
      - {label: "Test", name: "test", widget: "string", tagname: "h2"}
