backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections: # A list of collections the CMS should be able to edit
  - name: "teas" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tea" # Used in the UI, ie.: "New Post"
    folder: "content/teas"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tea.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number", required: true}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Ingredients", name: "ingredients", widget: "text"}
      - {label: "keywords", name: "keywords", widget: "string", required: false}
      - {label: "Tasting notes", name: "notes", widget: "text"}
      - {label: "Brewing guide", name: "guide", widget: "text"}
      - {label: "Colour", name: "color", widget: "text"}
      - label: "Carousel Images"
        name: "carousel_images"
        required: false
        label_singular: "Carousel image"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Caption", name: "caption", widget: "text"}
