backend:
  name: git-gateway
  repo: jrah/teadictionary
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections: # A list of collections the CMS should be able to edit
  - name: "Website Sections"
    label: "Website Sections"
    delete: false # Prevent users from deleting documents in this collection
    create: true
    editor:
      preview: false
    files:
      - name: "sections"
        label: "Sections"
        file: "content/sections.yml"
        description: "Website sections"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Heading", name: "heading", widget: "text", required: false}
          - {label: "Background image", name: "background_image", widget: "image", required: false}
          - {label: "Web browser preview image", name: "browser_preview", widget: "image", required: false}
          - {label: "Button text", name: "button_text", widget: "text", required: false}
          - {label: "Button href", name: "button_href", widget: "text", required: false}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - { label: "Date", name: "date", widget: "datetime" }
