backend:
  name: git-gateway
  repo: jrah/teadictionary
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "pages"
    folder: "content/pages"
    slug: "{{slug}}"
    create: true
    label: "Pages"
    label_singular: "Pages"
    fields:
      - {label: Title, name: title, widget: string}
